// TODO: instructions

export default [
  {
    name: 'finnishteacher.fi',
    _: [
      {
        name: 'Getting started!',
        _: [
          {
            name: 'Basic vocabulary',
            from: 'fi-FI',
            to: 'en-US',
            entries: {
              opettaja: 'teacher',
              suomi: 'finland',
              ruotsi: 'sweden',
              vanäjä: 'russia',
              vuotta: 'years',
              metsää: 'forest',
            },
          },
          {
            name: 'Greetings',
            from: 'fi-FI',
            to: 'en-US',
            entries: {
              'hei, moi, terve': 'hello',
              'hyvää huomenta': 'good morning',
              'hyvää päivää': 'good morning',
              'hyvää iltaa': 'good evening',
              'hyvää yötä': 'good night',
              'hei hei, moi moi, terve terve': 'bye bye',
              nähdään: 'see you',
              näkemiin: 'bye',
            },
          },
          {
            name: 'Colors',
            from: 'fi-FI',
            to: 'en-US',
            entries: {
              punainen: 'red',
              vihreä: 'green',
              sininen: 'blue',
              valkoinen: 'white',
              musta: 'black',
              harmaa: 'grey',
              oranssi: 'orange',
              keltainen: 'yellow',
              violetti: 'purple',
              vaaleanpunainen: 'light red',
              ruskea: 'brown',
              liila: 'pink',
            },
          },
          {
            name: 'Numbers',
            from: 'fi-FI',
            to: 'en-US',
            entries: {
              nolla: 'zero',
              yksi: 'one',
              kaksi: 'two',
              kolme: 'three',
              neljä: 'four',
              viisi: 'five',
              kuusi: 'six',
              seitsemän: 'seven',
              kahdeksan: 'eight',
              yhdeksän: 'nine',
              kymmenen: 'ten',
              yksitoista: 'eleven',
              kaksitoista: 'twelve',
              kolmetoista: 'thirteen',
              neljätoista: 'fourteen',
              viisitoista: 'fifteen',
              kuusitoista: 'sixteen',
              seitsemäntoista: 'seventeen',
              kahdeksantoista: 'eighteen',
              yhdeksäntoista: 'nineteen',
            },
          },
        ],
      },
    ],
  },
]
